### ISSUE TITLE
support for other models

### ISSUE THREAD

**Issue by shwu-nyunai** [CASIA-IVA-Lab/FLAP#5]
Are there any parallel efforts ongoing to add support for other models in FLAP?
models such as phi, Gemma, mistral, mistral, etc.

If so, what is the timeline for the same?

**Comment by an-yongqi** [comment]
I apologize for any inconvenience. Due to our current focus on other projects, we may not be able to extend support to additional models like phi, Gemma, and Mistral in the existing version of FLAP. We appreciate your interest and patience, and we recommend staying tuned for future updates regarding FLAP's development.

**Comment by shwu-nyunai** [comment]
thanks for the response. you may close this.
